---
- name: add apt_keys for additional repositories
  apt_key:
    id: "{{ item.signing_key }}"
    state: present
    keyserver: "keyserver.ubuntu.com"
  with_items: "{{ repos }}"

- name: add additional repositories to sources.list.d
  apt_repository:
    repo: "deb {{ item.uri }} {{ item.suite }} {{ item.components }}"
    filename: "{{ item.label }}"
    state: present
    validate_certs: yes
    update_cache: yes
  with_items: "{{ repos }}"
