---

- name: update cabal
  shell: cabal update  
  register: cabup
  changed_when: "not cabup.stdout|search('Skipping download: local and remote files match.')"


- name: compile and install tidal
  shell: cabal install tidal
  register: tidin
  changed_when: "not tidin.stdout|search('All the requested packages are already installed:')"
