---
- name: install packages
  apt: name={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
    - atom
    - cabal-install
    - haskell-stack
    - supercollider
    - zlib1g-dev
